 spring:
   datasource:
     url: jdbc:mysql://localhost:3306/checkout
     username: root
     password: root
     driver-class-name: com.mysql.cj.jdbc.Driver
   jpa:
     show-sql: true
     hibernate:
       ddl-auto: update

   mvc:
     path match:
       matching-strategy: ant_path_matcher
